# Generated by Django 5.2.5 on 2026-03-11 12:21

import django.core.validators
import friendsalbum2026.photo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[friendsalbum2026.photo.validators.validate_size])),
                ('description', models.TextField(blank=True, max_length=250, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('author', models.TextField(max_length=150, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_publication', models.DateField(auto_now=True)),
            ],
        ),
    ]
